name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qqy protobuf-compiler libprotobuf-dev

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Run lint
      run: make lint
